# -*- mode: python ; coding: utf-8 -*-

import os
import sys

# Add the current directory to Python path
sys.path.insert(0, os.path.abspath('.'))

a = Analysis(
    ['main.py'],
    pathex=['.', 'plugins'],
    binaries=[],
    datas=[
        ('plugins', 'plugins'),
        ('templates', 'templates'),
        ('static', 'static'),
        ('db.sqlite3', '.'),
        ('dvadmin', 'dvadmin'),
        ('application', 'application'),
    ],
    hiddenimports=[
        'application.settings', 
        'application.celery', 
        'application.asgi', 
        'application.wsgi', 
        'application.dispatch', 
        'application.routing', 
        'application.websocketConfig', 
        'dvadmin', 
        'dvadmin.utils', 
        'dvadmin.utils.pagination', 
        'dvadmin.utils.exception', 
        'dvadmin.system', 
        'plugins', 
        'plugins.brca',
        'plugins.brca.settings',
        'plugins.brca.models',
        'plugins.brca.views',
        'plugins.brca.serializers',
        'plugins.brca.urls',
        'plugins.brca.apps',
        'celery', 
        'celery.fixups', 
        'celery.app.trace', 
        'celery.backends', 
        'celery.loaders', 
        'celery.fixups.django', 
        'celery.loaders.app', 
        'celery.loaders.default', 
        'celery.loaders.base', 
        'celery.loaders.settings', 
        'celery.loaders.django', 
        'dvadmin.utils.middleware', 
        'django', 
        'django.conf', 
        'django.core.asgi', 
        'django.core.wsgi', 
        'django.core.handlers.asgi', 
        'django.core.handlers.wsgi', 
        'channels', 
        'channels.layers', 
        'channels_redis', 
        'uvicorn', 
        'gunicorn', 
        'gevent', 
        'pypinyin', 
        'openpyxl', 
        'whitenoise', 
        'drf_yasg', 
        'dvadmin3_celery', 
        'django_cors_headers', 
        'django_filter', 
        'django_ranged_response', 
        'django_restql', 
        'django_simple_captcha', 
        'django_timezone_field', 
        'djangorestframework_simplejwt', 
        'rest_framework_simplejwt.state',
        'websockets', 
        'user_agents', 
        'tzlocal', 
        'pyparsing', 
        'ua_parser', 
        'typing_extensions', 
        'six', 
        'requests', 
        'Pillow', 
        'mysqlclient', 
        'whitenoise.middleware',
        'whitenoise.storage'
    ],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='brca_backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
