name: Build Backend Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 你项目用的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r brca_system/backend/requirements.txt
          pip install pyinstaller

      - name: Build backend executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd brca_system/backend
          pyinstaller main.py --onefile --name brca_backend \
            --hidden-import=application.settings \
            --hidden-import=application.celery \
            --hidden-import=application.asgi \
            --hidden-import=application.wsgi \
            --hidden-import=application.dispatch \
            --hidden-import=application.routing \
            --hidden-import=application.websocketConfig \
            --hidden-import=dvadmin \
            --hidden-import=dvadmin.utils \
            --hidden-import=dvadmin.utils.pagination \
            --hidden-import=dvadmin.utils.exception \
            --hidden-import=dvadmin.system \
            --hidden-import=plugins \
            --hidden-import=plugins.brca \
            --hidden-import=celery \
            --hidden-import=celery.fixups \
            --hidden-import=celery.app.trace \
            --hidden-import=celery.backends \
            --hidden-import=celery.loaders \
            --hidden-import=celery.fixups.django \
            --hidden-import=celery.loaders.app \
            --hidden-import=celery.loaders.default \
            --hidden-import=celery.loaders.base \
            --hidden-import=celery.loaders.settings \
            --hidden-import=celery.loaders.django \
            --hidden-import=dvadmin.utils.middleware \
            --hidden-import=django \
            --hidden-import=django.conf \
            --hidden-import=django.core.asgi \
            --hidden-import=django.core.wsgi \
            --hidden-import=django.core.handlers.asgi \
            --hidden-import=django.core.handlers.wsgi \
            --hidden-import=channels \
            --hidden-import=channels.layers \
            --hidden-import=channels_redis \
            --hidden-import=uvicorn \
            --hidden-import=gunicorn \
            --hidden-import=gevent \
            --hidden-import=pypinyin \
            --hidden-import=openpyxl \
            --hidden-import=whitenoise \
            --hidden-import=drf_yasg \
            --hidden-import=dvadmin3_celery \
            --hidden-import=django_cors_headers \
            --hidden-import=django_filter \
            --hidden-import=django_ranged_response \
            --hidden-import=django_restql \
            --hidden-import=django_simple_captcha \
            --hidden-import=django_timezone_field \
            --hidden-import=djangorestframework_simplejwt \
            --hidden-import=websockets \
            --hidden-import=user_agents \
            --hidden-import=tzlocal \
            --hidden-import=pyparsing \
            --hidden-import=ua_parser \
            --hidden-import=typing_extensions \
            --hidden-import=six \
            --hidden-import=requests \
            --hidden-import=Pillow \
            --hidden-import=mysqlclient \
            --hidden-import=whitenoise.middleware

      - name: Build backend executable (Windows)
        if: runner.os == 'Windows'
        run: |
          cd brca_system\backend
          pyinstaller main.py --onefile --name brca_backend ^
            --hidden-import=application.settings ^
            --hidden-import=application.celery ^
            --hidden-import=application.asgi ^
            --hidden-import=application.wsgi ^
            --hidden-import=application.dispatch ^
            --hidden-import=application.routing ^
            --hidden-import=application.websocketConfig ^
            --hidden-import=dvadmin ^
            --hidden-import=dvadmin.utils ^
            --hidden-import=dvadmin.utils.pagination ^
            --hidden-import=dvadmin.utils.exception ^
            --hidden-import=dvadmin.system ^
            --hidden-import=plugins ^
            --hidden-import=plugins.brca ^
            --hidden-import=celery ^
            --hidden-import=celery.fixups ^
            --hidden-import=celery.app.trace ^
            --hidden-import=celery.backends ^
            --hidden-import=celery.loaders ^
            --hidden-import=celery.fixups.django ^
            --hidden-import=celery.loaders.app ^
            --hidden-import=celery.loaders.default ^
            --hidden-import=celery.loaders.base ^
            --hidden-import=celery.loaders.settings ^
            --hidden-import=celery.loaders.django ^
            --hidden-import=dvadmin.utils.middleware ^
            --hidden-import=django ^
            --hidden-import=django.conf ^
            --hidden-import=django.core.asgi ^
            --hidden-import=django.core.wsgi ^
            --hidden-import=django.core.handlers.asgi ^
            --hidden-import=django.core.handlers.wsgi ^
            --hidden-import=channels ^
            --hidden-import=channels.layers ^
            --hidden-import=channels_redis ^
            --hidden-import=uvicorn ^
            --hidden-import=gunicorn ^
            --hidden-import=gevent ^
            --hidden-import=pypinyin ^
            --hidden-import=openpyxl ^
            --hidden-import=whitenoise ^
            --hidden-import=drf_yasg ^
            --hidden-import=dvadmin3_celery ^
            --hidden-import=django_cors_headers ^
            --hidden-import=django_filter ^
            --hidden-import=django_ranged_response ^
            --hidden-import=django_restql ^
            --hidden-import=django_simple_captcha ^
            --hidden-import=django_timezone_field ^
            --hidden-import=djangorestframework_simplejwt ^
            --hidden-import=websockets ^
            --hidden-import=user_agents ^
            --hidden-import=tzlocal ^
            --hidden-import=pyparsing ^
            --hidden-import=ua_parser ^
            --hidden-import=typing_extensions ^
            --hidden-import=six ^
            --hidden-import=requests ^
            --hidden-import=Pillow ^
            --hidden-import=mysqlclient ^
            --hidden-import=whitenoise.middleware

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: brca_backend-${{ matrix.os }}
          path: brca_system/backend/dist/*