name: Build Backend Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 你项目用的 Python 版本

      - name: Clear cache and clean build
        run: |
          # 清理 Python 缓存
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -type f -name "*.pyc" -delete 2>/dev/null || true
          find . -type f -name "*.pyo" -delete 2>/dev/null || true
          
          # 清理 PyInstaller 缓存
          cd brca_system/backend
          rm -rf build dist __pycache__ .pytest_cache
          cd ../..

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r brca_system/backend/requirements.txt
          pip install pyinstaller

      - name: Build backend executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd brca_system/backend
          pyinstaller brca_backend.spec

      - name: Build backend executable (Windows)
        if: runner.os == 'Windows'
        run: |
          cd brca_system\backend
          pyinstaller brca_backend.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: brca_backend-${{ matrix.os }}
          path: brca_system/backend/dist/*